// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/url/url.proto

package url

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LongUrl       string                 `protobuf:"bytes,1,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateURLRequest) Reset() {
	*x = CreateURLRequest{}
	mi := &file_proto_url_url_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateURLRequest) ProtoMessage() {}

func (x *CreateURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_url_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateURLRequest.ProtoReflect.Descriptor instead.
func (*CreateURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_url_url_proto_rawDescGZIP(), []int{0}
}

func (x *CreateURLRequest) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

type CreateURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	LongUrl       string                 `protobuf:"bytes,3,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Id            int64                  `protobuf:"varint,5,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateURLResponse) Reset() {
	*x = CreateURLResponse{}
	mi := &file_proto_url_url_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateURLResponse) ProtoMessage() {}

func (x *CreateURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_url_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateURLResponse.ProtoReflect.Descriptor instead.
func (*CreateURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_url_url_proto_rawDescGZIP(), []int{1}
}

func (x *CreateURLResponse) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

func (x *CreateURLResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *CreateURLResponse) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

func (x *CreateURLResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CreateURLResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetURLRequest) Reset() {
	*x = GetURLRequest{}
	mi := &file_proto_url_url_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLRequest) ProtoMessage() {}

func (x *GetURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_url_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLRequest.ProtoReflect.Descriptor instead.
func (*GetURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_url_url_proto_rawDescGZIP(), []int{2}
}

func (x *GetURLRequest) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

type GetURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           *URL                   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetURLResponse) Reset() {
	*x = GetURLResponse{}
	mi := &file_proto_url_url_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLResponse) ProtoMessage() {}

func (x *GetURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_url_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLResponse.ProtoReflect.Descriptor instead.
func (*GetURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_url_url_proto_rawDescGZIP(), []int{3}
}

func (x *GetURLResponse) GetUrl() *URL {
	if x != nil {
		return x.Url
	}
	return nil
}

func (x *GetURLResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type ListURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"` // int64 user_id = 3;  // Uncomment when we add auth
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListURLsRequest) Reset() {
	*x = ListURLsRequest{}
	mi := &file_proto_url_url_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListURLsRequest) ProtoMessage() {}

func (x *ListURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_url_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListURLsRequest.ProtoReflect.Descriptor instead.
func (*ListURLsRequest) Descriptor() ([]byte, []int) {
	return file_proto_url_url_proto_rawDescGZIP(), []int{4}
}

func (x *ListURLsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListURLsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*URL                 `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListURLsResponse) Reset() {
	*x = ListURLsResponse{}
	mi := &file_proto_url_url_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListURLsResponse) ProtoMessage() {}

func (x *ListURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_url_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListURLsResponse.ProtoReflect.Descriptor instead.
func (*ListURLsResponse) Descriptor() ([]byte, []int) {
	return file_proto_url_url_proto_rawDescGZIP(), []int{5}
}

func (x *ListURLsResponse) GetUrls() []*URL {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *ListURLsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListURLsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type DeleteURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteURLRequest) Reset() {
	*x = DeleteURLRequest{}
	mi := &file_proto_url_url_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteURLRequest) ProtoMessage() {}

func (x *DeleteURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_url_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteURLRequest.ProtoReflect.Descriptor instead.
func (*DeleteURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_url_url_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteURLRequest) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

type DeleteURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteURLResponse) Reset() {
	*x = DeleteURLResponse{}
	mi := &file_proto_url_url_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteURLResponse) ProtoMessage() {}

func (x *DeleteURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_url_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteURLResponse.ProtoReflect.Descriptor instead.
func (*DeleteURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_url_url_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteURLResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type IncrementClicksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementClicksRequest) Reset() {
	*x = IncrementClicksRequest{}
	mi := &file_proto_url_url_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementClicksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementClicksRequest) ProtoMessage() {}

func (x *IncrementClicksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_url_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementClicksRequest.ProtoReflect.Descriptor instead.
func (*IncrementClicksRequest) Descriptor() ([]byte, []int) {
	return file_proto_url_url_proto_rawDescGZIP(), []int{8}
}

func (x *IncrementClicksRequest) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

type IncrementClicksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clicks        int64                  `protobuf:"varint,1,opt,name=clicks,proto3" json:"clicks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementClicksResponse) Reset() {
	*x = IncrementClicksResponse{}
	mi := &file_proto_url_url_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementClicksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementClicksResponse) ProtoMessage() {}

func (x *IncrementClicksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_url_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementClicksResponse.ProtoReflect.Descriptor instead.
func (*IncrementClicksResponse) Descriptor() ([]byte, []int) {
	return file_proto_url_url_proto_rawDescGZIP(), []int{9}
}

func (x *IncrementClicksResponse) GetClicks() int64 {
	if x != nil {
		return x.Clicks
	}
	return 0
}

type URL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ShortCode     string                 `protobuf:"bytes,2,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	LongUrl       string                 `protobuf:"bytes,3,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	Clicks        int64                  `protobuf:"varint,4,opt,name=clicks,proto3" json:"clicks,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URL) Reset() {
	*x = URL{}
	mi := &file_proto_url_url_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URL) ProtoMessage() {}

func (x *URL) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_url_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URL.ProtoReflect.Descriptor instead.
func (*URL) Descriptor() ([]byte, []int) {
	return file_proto_url_url_proto_rawDescGZIP(), []int{10}
}

func (x *URL) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *URL) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

func (x *URL) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

func (x *URL) GetClicks() int64 {
	if x != nil {
		return x.Clicks
	}
	return 0
}

func (x *URL) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *URL) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *URL) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

var File_proto_url_url_proto protoreflect.FileDescriptor

const file_proto_url_url_proto_rawDesc = "" +
	"\n" +
	"\x13proto/url/url.proto\x12\x03url\"-\n" +
	"\x10CreateURLRequest\x12\x19\n" +
	"\blong_url\x18\x01 \x01(\tR\alongUrl\"\x99\x01\n" +
	"\x11CreateURLResponse\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\x12\x19\n" +
	"\blong_url\x18\x03 \x01(\tR\alongUrl\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\x03R\x02id\".\n" +
	"\rGetURLRequest\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\"B\n" +
	"\x0eGetURLResponse\x12\x1a\n" +
	"\x03url\x18\x01 \x01(\v2\b.url.URLR\x03url\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"?\n" +
	"\x0fListURLsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"a\n" +
	"\x10ListURLsResponse\x12\x1c\n" +
	"\x04urls\x18\x01 \x03(\v2\b.url.URLR\x04urls\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"1\n" +
	"\x10DeleteURLRequest\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\"-\n" +
	"\x11DeleteURLResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"7\n" +
	"\x16IncrementClicksRequest\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\"1\n" +
	"\x17IncrementClicksResponse\x12\x16\n" +
	"\x06clicks\x18\x01 \x01(\x03R\x06clicks\"\xc2\x01\n" +
	"\x03URL\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"short_code\x18\x02 \x01(\tR\tshortCode\x12\x19\n" +
	"\blong_url\x18\x03 \x01(\tR\alongUrl\x12\x16\n" +
	"\x06clicks\x18\x04 \x01(\x03R\x06clicks\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive2\xbe\x02\n" +
	"\n" +
	"URLService\x12:\n" +
	"\tCreateURL\x12\x15.url.CreateURLRequest\x1a\x16.url.CreateURLResponse\x121\n" +
	"\x06GetURL\x12\x12.url.GetURLRequest\x1a\x13.url.GetURLResponse\x127\n" +
	"\bListURLs\x12\x14.url.ListURLsRequest\x1a\x15.url.ListURLsResponse\x12:\n" +
	"\tDeleteURL\x12\x15.url.DeleteURLRequest\x1a\x16.url.DeleteURLResponse\x12L\n" +
	"\x0fIncrementClicks\x12\x1b.url.IncrementClicksRequest\x1a\x1c.url.IncrementClicksResponseB+Z)github.com/Varun5711/shorternit/proto/urlb\x06proto3"

var (
	file_proto_url_url_proto_rawDescOnce sync.Once
	file_proto_url_url_proto_rawDescData []byte
)

func file_proto_url_url_proto_rawDescGZIP() []byte {
	file_proto_url_url_proto_rawDescOnce.Do(func() {
		file_proto_url_url_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_url_url_proto_rawDesc), len(file_proto_url_url_proto_rawDesc)))
	})
	return file_proto_url_url_proto_rawDescData
}

var file_proto_url_url_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_url_url_proto_goTypes = []any{
	(*CreateURLRequest)(nil),        // 0: url.CreateURLRequest
	(*CreateURLResponse)(nil),       // 1: url.CreateURLResponse
	(*GetURLRequest)(nil),           // 2: url.GetURLRequest
	(*GetURLResponse)(nil),          // 3: url.GetURLResponse
	(*ListURLsRequest)(nil),         // 4: url.ListURLsRequest
	(*ListURLsResponse)(nil),        // 5: url.ListURLsResponse
	(*DeleteURLRequest)(nil),        // 6: url.DeleteURLRequest
	(*DeleteURLResponse)(nil),       // 7: url.DeleteURLResponse
	(*IncrementClicksRequest)(nil),  // 8: url.IncrementClicksRequest
	(*IncrementClicksResponse)(nil), // 9: url.IncrementClicksResponse
	(*URL)(nil),                     // 10: url.URL
}
var file_proto_url_url_proto_depIdxs = []int32{
	10, // 0: url.GetURLResponse.url:type_name -> url.URL
	10, // 1: url.ListURLsResponse.urls:type_name -> url.URL
	0,  // 2: url.URLService.CreateURL:input_type -> url.CreateURLRequest
	2,  // 3: url.URLService.GetURL:input_type -> url.GetURLRequest
	4,  // 4: url.URLService.ListURLs:input_type -> url.ListURLsRequest
	6,  // 5: url.URLService.DeleteURL:input_type -> url.DeleteURLRequest
	8,  // 6: url.URLService.IncrementClicks:input_type -> url.IncrementClicksRequest
	1,  // 7: url.URLService.CreateURL:output_type -> url.CreateURLResponse
	3,  // 8: url.URLService.GetURL:output_type -> url.GetURLResponse
	5,  // 9: url.URLService.ListURLs:output_type -> url.ListURLsResponse
	7,  // 10: url.URLService.DeleteURL:output_type -> url.DeleteURLResponse
	9,  // 11: url.URLService.IncrementClicks:output_type -> url.IncrementClicksResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_url_url_proto_init() }
func file_proto_url_url_proto_init() {
	if File_proto_url_url_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_url_url_proto_rawDesc), len(file_proto_url_url_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_url_url_proto_goTypes,
		DependencyIndexes: file_proto_url_url_proto_depIdxs,
		MessageInfos:      file_proto_url_url_proto_msgTypes,
	}.Build()
	File_proto_url_url_proto = out.File
	file_proto_url_url_proto_goTypes = nil
	file_proto_url_url_proto_depIdxs = nil
}
