// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: analytics.proto

package analytics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrackClickRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The short code that was clicked
	ShortCode string `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	// IP address of the visitor
	IpAddress string `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// User-Agent string (browser info)
	UserAgent string `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	// Referer header (where they came from)
	Referer string `protobuf:"bytes,4,opt,name=referer,proto3" json:"referer,omitempty"`
	// Timestamp of the click (Unix seconds)
	Timestamp     int64 `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackClickRequest) Reset() {
	*x = TrackClickRequest{}
	mi := &file_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackClickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackClickRequest) ProtoMessage() {}

func (x *TrackClickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackClickRequest.ProtoReflect.Descriptor instead.
func (*TrackClickRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *TrackClickRequest) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

func (x *TrackClickRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *TrackClickRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *TrackClickRequest) GetReferer() string {
	if x != nil {
		return x.Referer
	}
	return ""
}

func (x *TrackClickRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type TrackClickResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the click was recorded successfully
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Unique click ID (for debugging)
	ClickId       string `protobuf:"bytes,2,opt,name=click_id,json=clickId,proto3" json:"click_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackClickResponse) Reset() {
	*x = TrackClickResponse{}
	mi := &file_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackClickResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackClickResponse) ProtoMessage() {}

func (x *TrackClickResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackClickResponse.ProtoReflect.Descriptor instead.
func (*TrackClickResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *TrackClickResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TrackClickResponse) GetClickId() string {
	if x != nil {
		return x.ClickId
	}
	return ""
}

type GetStatsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The short code to get stats for
	ShortCode string `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	// Optional: Time range (Unix timestamps)
	StartTime     int64 `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64 `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *GetStatsRequest) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

func (x *GetStatsRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetStatsRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type GetStatsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ShortCode      string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	TotalClicks    int64                  `protobuf:"varint,2,opt,name=total_clicks,json=totalClicks,proto3" json:"total_clicks,omitempty"`
	UniqueVisitors int64                  `protobuf:"varint,3,opt,name=unique_visitors,json=uniqueVisitors,proto3" json:"unique_visitors,omitempty"`
	Countries      []*CountryStat         `protobuf:"bytes,4,rep,name=countries,proto3" json:"countries,omitempty"`
	Referrers      []*RefererStat         `protobuf:"bytes,5,rep,name=referrers,proto3" json:"referrers,omitempty"`
	DeviceStats    *DeviceStats           `protobuf:"bytes,6,opt,name=device_stats,json=deviceStats,proto3" json:"device_stats,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatsResponse) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

func (x *GetStatsResponse) GetTotalClicks() int64 {
	if x != nil {
		return x.TotalClicks
	}
	return 0
}

func (x *GetStatsResponse) GetUniqueVisitors() int64 {
	if x != nil {
		return x.UniqueVisitors
	}
	return 0
}

func (x *GetStatsResponse) GetCountries() []*CountryStat {
	if x != nil {
		return x.Countries
	}
	return nil
}

func (x *GetStatsResponse) GetReferrers() []*RefererStat {
	if x != nil {
		return x.Referrers
	}
	return nil
}

func (x *GetStatsResponse) GetDeviceStats() *DeviceStats {
	if x != nil {
		return x.DeviceStats
	}
	return nil
}

type CountryStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountryCode   string                 `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	CountryName   string                 `protobuf:"bytes,2,opt,name=country_name,json=countryName,proto3" json:"country_name,omitempty"`
	ClickCount    int64                  `protobuf:"varint,3,opt,name=click_count,json=clickCount,proto3" json:"click_count,omitempty"`
	Percentage    float32                `protobuf:"fixed32,4,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountryStat) Reset() {
	*x = CountryStat{}
	mi := &file_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountryStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountryStat) ProtoMessage() {}

func (x *CountryStat) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountryStat.ProtoReflect.Descriptor instead.
func (*CountryStat) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *CountryStat) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *CountryStat) GetCountryName() string {
	if x != nil {
		return x.CountryName
	}
	return ""
}

func (x *CountryStat) GetClickCount() int64 {
	if x != nil {
		return x.ClickCount
	}
	return 0
}

func (x *CountryStat) GetPercentage() float32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

type RefererStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Referer       string                 `protobuf:"bytes,1,opt,name=referer,proto3" json:"referer,omitempty"`
	ClickCount    int64                  `protobuf:"varint,2,opt,name=click_count,json=clickCount,proto3" json:"click_count,omitempty"`
	Percentage    float32                `protobuf:"fixed32,3,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefererStat) Reset() {
	*x = RefererStat{}
	mi := &file_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefererStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefererStat) ProtoMessage() {}

func (x *RefererStat) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefererStat.ProtoReflect.Descriptor instead.
func (*RefererStat) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *RefererStat) GetReferer() string {
	if x != nil {
		return x.Referer
	}
	return ""
}

func (x *RefererStat) GetClickCount() int64 {
	if x != nil {
		return x.ClickCount
	}
	return 0
}

func (x *RefererStat) GetPercentage() float32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

type DeviceStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        int64                  `protobuf:"varint,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Desktop       int64                  `protobuf:"varint,2,opt,name=desktop,proto3" json:"desktop,omitempty"`
	Tablet        int64                  `protobuf:"varint,3,opt,name=tablet,proto3" json:"tablet,omitempty"`
	Other         int64                  `protobuf:"varint,4,opt,name=other,proto3" json:"other,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceStats) Reset() {
	*x = DeviceStats{}
	mi := &file_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceStats) ProtoMessage() {}

func (x *DeviceStats) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceStats.ProtoReflect.Descriptor instead.
func (*DeviceStats) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *DeviceStats) GetMobile() int64 {
	if x != nil {
		return x.Mobile
	}
	return 0
}

func (x *DeviceStats) GetDesktop() int64 {
	if x != nil {
		return x.Desktop
	}
	return 0
}

func (x *DeviceStats) GetTablet() int64 {
	if x != nil {
		return x.Tablet
	}
	return 0
}

func (x *DeviceStats) GetOther() int64 {
	if x != nil {
		return x.Other
	}
	return 0
}

type GetTimeSeriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	StartTime     int64                  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Granularity   string                 `protobuf:"bytes,4,opt,name=granularity,proto3" json:"granularity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimeSeriesRequest) Reset() {
	*x = GetTimeSeriesRequest{}
	mi := &file_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimeSeriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimeSeriesRequest) ProtoMessage() {}

func (x *GetTimeSeriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimeSeriesRequest.ProtoReflect.Descriptor instead.
func (*GetTimeSeriesRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *GetTimeSeriesRequest) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

func (x *GetTimeSeriesRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetTimeSeriesRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *GetTimeSeriesRequest) GetGranularity() string {
	if x != nil {
		return x.Granularity
	}
	return ""
}

type GetTimeSeriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*TimeSeriesPoint     `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimeSeriesResponse) Reset() {
	*x = GetTimeSeriesResponse{}
	mi := &file_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimeSeriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimeSeriesResponse) ProtoMessage() {}

func (x *GetTimeSeriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimeSeriesResponse.ProtoReflect.Descriptor instead.
func (*GetTimeSeriesResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *GetTimeSeriesResponse) GetPoints() []*TimeSeriesPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type TimeSeriesPoint struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Timestamp      int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Clicks         int64                  `protobuf:"varint,2,opt,name=clicks,proto3" json:"clicks,omitempty"`
	UniqueVisitors int64                  `protobuf:"varint,3,opt,name=unique_visitors,json=uniqueVisitors,proto3" json:"unique_visitors,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TimeSeriesPoint) Reset() {
	*x = TimeSeriesPoint{}
	mi := &file_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSeriesPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSeriesPoint) ProtoMessage() {}

func (x *TimeSeriesPoint) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSeriesPoint.ProtoReflect.Descriptor instead.
func (*TimeSeriesPoint) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{9}
}

func (x *TimeSeriesPoint) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TimeSeriesPoint) GetClicks() int64 {
	if x != nil {
		return x.Clicks
	}
	return 0
}

func (x *TimeSeriesPoint) GetUniqueVisitors() int64 {
	if x != nil {
		return x.UniqueVisitors
	}
	return 0
}

type GetGeoStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGeoStatsRequest) Reset() {
	*x = GetGeoStatsRequest{}
	mi := &file_analytics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGeoStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGeoStatsRequest) ProtoMessage() {}

func (x *GetGeoStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGeoStatsRequest.ProtoReflect.Descriptor instead.
func (*GetGeoStatsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{10}
}

func (x *GetGeoStatsRequest) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

func (x *GetGeoStatsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetGeoStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Countries     []*CountryStat         `protobuf:"bytes,1,rep,name=countries,proto3" json:"countries,omitempty"`
	Cities        []*CityStat            `protobuf:"bytes,2,rep,name=cities,proto3" json:"cities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGeoStatsResponse) Reset() {
	*x = GetGeoStatsResponse{}
	mi := &file_analytics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGeoStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGeoStatsResponse) ProtoMessage() {}

func (x *GetGeoStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGeoStatsResponse.ProtoReflect.Descriptor instead.
func (*GetGeoStatsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{11}
}

func (x *GetGeoStatsResponse) GetCountries() []*CountryStat {
	if x != nil {
		return x.Countries
	}
	return nil
}

func (x *GetGeoStatsResponse) GetCities() []*CityStat {
	if x != nil {
		return x.Cities
	}
	return nil
}

type CityStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	CountryCode   string                 `protobuf:"bytes,2,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	ClickCount    int64                  `protobuf:"varint,3,opt,name=click_count,json=clickCount,proto3" json:"click_count,omitempty"`
	Percentage    float32                `protobuf:"fixed32,4,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CityStat) Reset() {
	*x = CityStat{}
	mi := &file_analytics_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CityStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityStat) ProtoMessage() {}

func (x *CityStat) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityStat.ProtoReflect.Descriptor instead.
func (*CityStat) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{12}
}

func (x *CityStat) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CityStat) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *CityStat) GetClickCount() int64 {
	if x != nil {
		return x.ClickCount
	}
	return 0
}

func (x *CityStat) GetPercentage() float32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

var File_analytics_proto protoreflect.FileDescriptor

const file_analytics_proto_rawDesc = "" +
	"\n" +
	"\x0fanalytics.proto\x12\tanalytics\"\xa8\x01\n" +
	"\x11TrackClickRequest\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x03 \x01(\tR\tuserAgent\x12\x18\n" +
	"\areferer\x18\x04 \x01(\tR\areferer\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"I\n" +
	"\x12TrackClickResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\bclick_id\x18\x02 \x01(\tR\aclickId\"j\n" +
	"\x0fGetStatsRequest\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x03R\aendTime\"\xa4\x02\n" +
	"\x10GetStatsResponse\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\x12!\n" +
	"\ftotal_clicks\x18\x02 \x01(\x03R\vtotalClicks\x12'\n" +
	"\x0funique_visitors\x18\x03 \x01(\x03R\x0euniqueVisitors\x124\n" +
	"\tcountries\x18\x04 \x03(\v2\x16.analytics.CountryStatR\tcountries\x124\n" +
	"\treferrers\x18\x05 \x03(\v2\x16.analytics.RefererStatR\treferrers\x129\n" +
	"\fdevice_stats\x18\x06 \x01(\v2\x16.analytics.DeviceStatsR\vdeviceStats\"\x94\x01\n" +
	"\vCountryStat\x12!\n" +
	"\fcountry_code\x18\x01 \x01(\tR\vcountryCode\x12!\n" +
	"\fcountry_name\x18\x02 \x01(\tR\vcountryName\x12\x1f\n" +
	"\vclick_count\x18\x03 \x01(\x03R\n" +
	"clickCount\x12\x1e\n" +
	"\n" +
	"percentage\x18\x04 \x01(\x02R\n" +
	"percentage\"h\n" +
	"\vRefererStat\x12\x18\n" +
	"\areferer\x18\x01 \x01(\tR\areferer\x12\x1f\n" +
	"\vclick_count\x18\x02 \x01(\x03R\n" +
	"clickCount\x12\x1e\n" +
	"\n" +
	"percentage\x18\x03 \x01(\x02R\n" +
	"percentage\"m\n" +
	"\vDeviceStats\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\x03R\x06mobile\x12\x18\n" +
	"\adesktop\x18\x02 \x01(\x03R\adesktop\x12\x16\n" +
	"\x06tablet\x18\x03 \x01(\x03R\x06tablet\x12\x14\n" +
	"\x05other\x18\x04 \x01(\x03R\x05other\"\x91\x01\n" +
	"\x14GetTimeSeriesRequest\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x03R\aendTime\x12 \n" +
	"\vgranularity\x18\x04 \x01(\tR\vgranularity\"K\n" +
	"\x15GetTimeSeriesResponse\x122\n" +
	"\x06points\x18\x01 \x03(\v2\x1a.analytics.TimeSeriesPointR\x06points\"p\n" +
	"\x0fTimeSeriesPoint\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06clicks\x18\x02 \x01(\x03R\x06clicks\x12'\n" +
	"\x0funique_visitors\x18\x03 \x01(\x03R\x0euniqueVisitors\"I\n" +
	"\x12GetGeoStatsRequest\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"x\n" +
	"\x13GetGeoStatsResponse\x124\n" +
	"\tcountries\x18\x01 \x03(\v2\x16.analytics.CountryStatR\tcountries\x12+\n" +
	"\x06cities\x18\x02 \x03(\v2\x13.analytics.CityStatR\x06cities\"\x82\x01\n" +
	"\bCityStat\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12!\n" +
	"\fcountry_code\x18\x02 \x01(\tR\vcountryCode\x12\x1f\n" +
	"\vclick_count\x18\x03 \x01(\x03R\n" +
	"clickCount\x12\x1e\n" +
	"\n" +
	"percentage\x18\x04 \x01(\x02R\n" +
	"percentage2\xc4\x02\n" +
	"\x10AnalyticsService\x12I\n" +
	"\n" +
	"TrackClick\x12\x1c.analytics.TrackClickRequest\x1a\x1d.analytics.TrackClickResponse\x12C\n" +
	"\bGetStats\x12\x1a.analytics.GetStatsRequest\x1a\x1b.analytics.GetStatsResponse\x12R\n" +
	"\rGetTimeSeries\x12\x1f.analytics.GetTimeSeriesRequest\x1a .analytics.GetTimeSeriesResponse\x12L\n" +
	"\vGetGeoStats\x12\x1d.analytics.GetGeoStatsRequest\x1a\x1e.analytics.GetGeoStatsResponseB1Z/github.com/Varun5711/shorternit/proto/analyticsb\x06proto3"

var (
	file_analytics_proto_rawDescOnce sync.Once
	file_analytics_proto_rawDescData []byte
)

func file_analytics_proto_rawDescGZIP() []byte {
	file_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)))
	})
	return file_analytics_proto_rawDescData
}

var file_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_analytics_proto_goTypes = []any{
	(*TrackClickRequest)(nil),     // 0: analytics.TrackClickRequest
	(*TrackClickResponse)(nil),    // 1: analytics.TrackClickResponse
	(*GetStatsRequest)(nil),       // 2: analytics.GetStatsRequest
	(*GetStatsResponse)(nil),      // 3: analytics.GetStatsResponse
	(*CountryStat)(nil),           // 4: analytics.CountryStat
	(*RefererStat)(nil),           // 5: analytics.RefererStat
	(*DeviceStats)(nil),           // 6: analytics.DeviceStats
	(*GetTimeSeriesRequest)(nil),  // 7: analytics.GetTimeSeriesRequest
	(*GetTimeSeriesResponse)(nil), // 8: analytics.GetTimeSeriesResponse
	(*TimeSeriesPoint)(nil),       // 9: analytics.TimeSeriesPoint
	(*GetGeoStatsRequest)(nil),    // 10: analytics.GetGeoStatsRequest
	(*GetGeoStatsResponse)(nil),   // 11: analytics.GetGeoStatsResponse
	(*CityStat)(nil),              // 12: analytics.CityStat
}
var file_analytics_proto_depIdxs = []int32{
	4,  // 0: analytics.GetStatsResponse.countries:type_name -> analytics.CountryStat
	5,  // 1: analytics.GetStatsResponse.referrers:type_name -> analytics.RefererStat
	6,  // 2: analytics.GetStatsResponse.device_stats:type_name -> analytics.DeviceStats
	9,  // 3: analytics.GetTimeSeriesResponse.points:type_name -> analytics.TimeSeriesPoint
	4,  // 4: analytics.GetGeoStatsResponse.countries:type_name -> analytics.CountryStat
	12, // 5: analytics.GetGeoStatsResponse.cities:type_name -> analytics.CityStat
	0,  // 6: analytics.AnalyticsService.TrackClick:input_type -> analytics.TrackClickRequest
	2,  // 7: analytics.AnalyticsService.GetStats:input_type -> analytics.GetStatsRequest
	7,  // 8: analytics.AnalyticsService.GetTimeSeries:input_type -> analytics.GetTimeSeriesRequest
	10, // 9: analytics.AnalyticsService.GetGeoStats:input_type -> analytics.GetGeoStatsRequest
	1,  // 10: analytics.AnalyticsService.TrackClick:output_type -> analytics.TrackClickResponse
	3,  // 11: analytics.AnalyticsService.GetStats:output_type -> analytics.GetStatsResponse
	8,  // 12: analytics.AnalyticsService.GetTimeSeries:output_type -> analytics.GetTimeSeriesResponse
	11, // 13: analytics.AnalyticsService.GetGeoStats:output_type -> analytics.GetGeoStatsResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_analytics_proto_init() }
func file_analytics_proto_init() {
	if File_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_proto_depIdxs,
		MessageInfos:      file_analytics_proto_msgTypes,
	}.Build()
	File_analytics_proto = out.File
	file_analytics_proto_goTypes = nil
	file_analytics_proto_depIdxs = nil
}
